version: '3.7'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - "APP_DEBUG=true"
      - "JAEGER_HOST=jaeger"
      - "JAEGER_PORT=6831"
      - "JAEGER_SERVICE_NAME=php-golang-blog-parser"
  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - "COLLECTOR_ZIPKIN_HTTP_PORT=9411"
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
